management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
spring:  
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
